@startuml

left to right direction

actor :学生:
actor :老师:

package 学生用例 {
    学生 --> (登录系统)
    学生 --> (退出系统)
    学生 --> (选课)
    学生 --> (设置实验地址)
    学生 --> (查看个人成绩)
}

package 老师用例 {
    老师 --> (维护选择课程的信息)
    (维护选择课程的信息) .> (选择上课班级) : <<extends>>
    老师 --> (选择上课班级)
    老师 --> (查看学生成绩)

    package 实验成绩用例 {
        老师 --> (实验过程叙述详细程度)
        老师 --> (实验中涉及的概念是否正确)
        老师 --> (实验的语言表达是否准确)
        老师 --> (实验的结构是否严谨、条理是否清晰)
        老师 --> (实验的逻辑性是否合理)
        老师 --> (实验是否存在抄袭)
        (实验过程叙述详细程度) .> (评阅实验) : <<include>>
        (实验中涉及的概念是否正确) .> (评阅实验) : <<include>>
        (实验的语言表达是否准确) .> (评阅实验) : <<include>>
        (实验的结构是否严谨、条理是否清晰) .> (评阅实验) : <<include>>
        (实验的逻辑性是否合理) .> (评阅实验) : <<include>>
        (实验是否存在抄袭) .> (评阅实验) : <<include>>
        (评阅实验) --> (计算实验平均成绩) : <<include>>
        (评阅实验) --> (实验文字评价) : <<include>>
    }
}

@enduml