@startuml
skinparam backgroundColor #00FF7F


left to right direction

actor :用户:
actor :学生:
actor :老师:

package 用户 {
    用户 --> (登录系统)
    用户 --> (退出系统)
    用户 --> (修改信息)
}

package 学生 {
    学生 --> (查看自己成绩)
    学生 --> (修改GitHub用户名)
    学生 --> (选课)
}

package 老师 {
    老师 --> (选择课程)
    老师 --> (选择上课班级)
    老师 --> (查看学生成绩)
    老师 --> (评定最终成绩)

    package 成绩评分标准用例分析 {
        老师 --> (实验是否完整)
        老师 --> (实验结构是否严谨)
        老师 --> (实验文档是否合格)
        (实验是否完整) --> (实验打分)
        (实验结构是否严谨) --> (实验打分)
        (实验文档是否合格) --> (实验打分)
        (实验打分) --> (计算实验平均成绩)
        (实验打分) --> (实验文字评价)
    }
}

student --> 学生
teacher --> 老师
user --> 用户


@enduml